language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./gradlew
  bintrayUpload --stacktrace
env:
  global:
  - secure: MtvMbfR87RyqZBh7pKPDYWDTV8uDjw/9p67P3CkpWFnsTX3ASrObBPXk/GmS1GEz9m3n3bUSywopGveyu5g5Vd7qmxy2RpwTcPITKJAUfxoZLUDOIxVxbLzjGgBr6u230ifD+B325dp1UI/s+5x9aKMIpXrtY4fRb5HN6SUJwYzHRopGZvULfwZAtTocXci3Yky4FmURI1YFNy0LdlAH2zWO4NafJrDt6zLWDbK3DqQLSvDyDpAGAxs0atXgS+kfluceN0Tf2R7qNKVru5hDsWrdIMgzp9E967Fph21mB8kHhX4fzZwsIpzXNeEKGiYNVe+ybObZ6ryImWfQsJW3j3PrhirSLgeqB+1Gv307MFihPLSnDbdfeBKuSYLD7SZoGgf/aokYvil5KM+Fb3WTRjOzNOqiqf61CmNk9WbSewZUM9yp4xXcC+RbbzW1zcs5rnvPiQcDzn20i+YhwnTSLg6WNOeAMLN9sYiAwevNTu5AlcKnaHN/xcoEcNwvroml9Hp227bWSvghgqexs6jxVcMbj5bZX+z+IFv7CRFWtqkV/wAm5GiacoImzpyWo8gQZ1tWkmaQZRP/g3QcScw/g3EoiPWQtwmA9pzNLoZtio0BIgaiTL4zJrdFp1xHb5hhTMr3Ec9UzolR4vG6LpX0qJXb/JsO/h9ajFtedflSYQM=
  - secure: r6MrK5xLYKJ4EcWPvifKcYo4Mxqq/mXO11pxiypGNLbNQ7XD8yl+6Z20Oo/U63K3uPaZ6/L1pZiuTkH/8Yj68usOHsKNK9TVh/P64RNHIPizrT/iq0tZjZ9Vnq9wai4ApQQHhcpee2xlQFZNlS5ZvfPWyvJEm9ayc4ITWTUbp3YeBZk8z6Rt/LKRym2XTS1vUevk0wrTErvbpB7vpiEWx3DEfaCYU9AntBL3mYwCiR0jWzl7aBdEzz0EYgfCcu8gdLVKXkh42YLH9TDVNxDFYM+XJ83wDnEwJpgBrJ1OuwIb4yXVHflyKqqFZ9F7L9s/i12u1asABf1VCHm9KpHjRqKd+knFiR4Pm8hF8V5y3Mjb4gkOWGjCdrYfIyh2FrkNSpgOPuwBntIBRRuVXCdpGyVc1aP/bHE4UOh/f4f9EpfNo9KTV0Pu+ZY58+bcFdHR7xALccaOKLbF232+BIJzzrwgq5HE136/jnOxeCl+73yb8UhcqFWP+zv7DDN5YYpjc24zNbj4k5GO3mMHmI4cdZ+9OIoMJnGiGLUgewcc5r4kDvLCmYewAIIVjcTzkvbUJLEsFgf9d5zgHKZ7ZyAntcAkkyHvPEJYQhjV7JiQMdgcxF3W44AXvglNxeYHO2V1mMou4paXkTIm5Ryy+96ZiAvyCylNZ2D+Bg/RzIu1cnU=
